### ISSUE TITLE
Couldn't find pack in packagist

### ISSUE THREAD

**Issue by maxhelias** [DbToolsBundle/pack-fr-fr#2]
Hi!
First of all, thanks for creating db tool, it looks promising.

The pack-fr isn't available on packagist, so we cannot require it. See : 

![Capture d’écran 2024-05-29 à 18 01 50](https://github.com/DbToolsBundle/pack-fr-fr/assets/12966574/d03bd89e-7fd2-4780-8ea8-f86217a18450)

Is it possible to make it available ? Or is this intended to delcare the repo in the composer.json ?

**Comment by SimonMellerin** [comment]
Hi,

sorry for the delay, I hadn't seen the issue. Pakcage has been registered with the wrong name, should be good now.
